// Generated by the ProtocolType buffer compiler.  DO NOT EDIT!
// source: ProtoService.proto

package com.example.sofa.rpc.protobuf;

/**
 * Protobuf type {@code com.example.sofa.rpc.protobuf.EchoResponse}
 */
public final class EchoResponse extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:com.example.sofa.rpc.protobuf.EchoResponse)
		EchoResponseOrBuilder {
	private static final long serialVersionUID = 0L;

	// Use EchoResponse.newBuilder() to construct.
	private EchoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private EchoResponse() {
		code_ = 0;
		message_ = "";
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	private EchoResponse(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		}
		int mutable_bitField0_ = 0;
		com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				case 8: {

					code_ = input.readInt32();
					break;
				}
				case 18: {
					java.lang.String s = input.readStringRequireUtf8();

					message_ = s;
					break;
				}
				default: {
					if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
						done = true;
					}
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		} catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		} finally {
			this.unknownFields = unknownFields.build();
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoResponse_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.example.sofa.rpc.protobuf.EchoResponse.class,
						com.example.sofa.rpc.protobuf.EchoResponse.Builder.class);
	}

	public static final int CODE_FIELD_NUMBER = 1;
	private int code_;

	/**
	 * <code>int32 code = 1;</code>
	 */
	@Override
	public int getCode() {
		return code_;
	}

	public static final int MESSAGE_FIELD_NUMBER = 2;
	private volatile java.lang.Object message_;

	/**
	 * <code>string message = 2;</code>
	 */
	@Override
	public java.lang.String getMessage() {
		java.lang.Object ref = message_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			message_ = s;
			return s;
		}
	}

	/**
	 * <code>string message = 2;</code>
	 */
	@Override
	public com.google.protobuf.ByteString getMessageBytes() {
		java.lang.Object ref = message_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			message_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (code_ != 0) {
			output.writeInt32(1, code_);
		}
		if (!getMessageBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
		}
		unknownFields.writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (code_ != 0) {
			size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, code_);
		}
		if (!getMessageBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
		}
		size += unknownFields.getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof com.example.sofa.rpc.protobuf.EchoResponse)) {
			return super.equals(obj);
		}
		com.example.sofa.rpc.protobuf.EchoResponse other = (com.example.sofa.rpc.protobuf.EchoResponse) obj;

		boolean result = true;
		result = result && (getCode() == other.getCode());
		result = result && getMessage().equals(other.getMessage());
		result = result && unknownFields.equals(other.unknownFields);
		return result;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + CODE_FIELD_NUMBER;
		hash = (53 * hash) + getCode();
		hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
		hash = (53 * hash) + getMessage().hashCode();
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.example.sofa.rpc.protobuf.EchoResponse prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code com.example.sofa.rpc.protobuf.EchoResponse}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:com.example.sofa.rpc.protobuf.EchoResponse)
			com.example.sofa.rpc.protobuf.EchoResponseOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoResponse_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.example.sofa.rpc.protobuf.EchoResponse.class,
							com.example.sofa.rpc.protobuf.EchoResponse.Builder.class);
		}

		// Construct using com.example.sofa.rpc.protobuf.EchoResponse.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			code_ = 0;

			message_ = "";

			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoResponse_descriptor;
		}

		@java.lang.Override
		public com.example.sofa.rpc.protobuf.EchoResponse getDefaultInstanceForType() {
			return com.example.sofa.rpc.protobuf.EchoResponse.getDefaultInstance();
		}

		@java.lang.Override
		public com.example.sofa.rpc.protobuf.EchoResponse build() {
			com.example.sofa.rpc.protobuf.EchoResponse result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public com.example.sofa.rpc.protobuf.EchoResponse buildPartial() {
			com.example.sofa.rpc.protobuf.EchoResponse result = new com.example.sofa.rpc.protobuf.EchoResponse(this);
			result.code_ = code_;
			result.message_ = message_;
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.example.sofa.rpc.protobuf.EchoResponse) {
				return mergeFrom((com.example.sofa.rpc.protobuf.EchoResponse) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.example.sofa.rpc.protobuf.EchoResponse other) {
			if (other == com.example.sofa.rpc.protobuf.EchoResponse.getDefaultInstance())
				return this;
			if (other.getCode() != 0) {
				setCode(other.getCode());
			}
			if (!other.getMessage().isEmpty()) {
				message_ = other.message_;
				onChanged();
			}
			this.mergeUnknownFields(other.unknownFields);
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.example.sofa.rpc.protobuf.EchoResponse parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.example.sofa.rpc.protobuf.EchoResponse) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private int code_;

		/**
		 * <code>int32 code = 1;</code>
		 */
		@Override
		public int getCode() {
			return code_;
		}

		/**
		 * <code>int32 code = 1;</code>
		 */
		public Builder setCode(int value) {

			code_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>int32 code = 1;</code>
		 */
		public Builder clearCode() {

			code_ = 0;
			onChanged();
			return this;
		}

		private java.lang.Object message_ = "";

		/**
		 * <code>string message = 2;</code>
		 */
		@Override
		public java.lang.String getMessage() {
			java.lang.Object ref = message_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				message_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string message = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getMessageBytes() {
			java.lang.Object ref = message_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				message_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string message = 2;</code>
		 */
		public Builder setMessage(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			message_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>string message = 2;</code>
		 */
		public Builder clearMessage() {

			message_ = getDefaultInstance().getMessage();
			onChanged();
			return this;
		}

		/**
		 * <code>string message = 2;</code>
		 */
		public Builder setMessageBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			message_ = value;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFieldsProto3(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:com.example.sofa.rpc.protobuf.EchoResponse)
	}

	// @@protoc_insertion_point(class_scope:com.example.sofa.rpc.protobuf.EchoResponse)
	private static final com.example.sofa.rpc.protobuf.EchoResponse DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.example.sofa.rpc.protobuf.EchoResponse();
	}

	public static com.example.sofa.rpc.protobuf.EchoResponse getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<EchoResponse> PARSER = new com.google.protobuf.AbstractParser<EchoResponse>() {
		@java.lang.Override
		public EchoResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new EchoResponse(input, extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<EchoResponse> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<EchoResponse> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public com.example.sofa.rpc.protobuf.EchoResponse getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
