// Generated by the ProtocolType buffer compiler.  DO NOT EDIT!
// source: ProtoService.proto

package com.example.sofa.rpc.protobuf;

public interface EchoResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:com.example.sofa.rpc.protobuf.EchoResponse)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>int32 code = 1;</code>
	 */
	int getCode();

	/**
	 * <code>string message = 2;</code>
	 */
	java.lang.String getMessage();

	/**
	 * <code>string message = 2;</code>
	 */
	com.google.protobuf.ByteString getMessageBytes();
}
