// Generated by the ProtocolType buffer compiler.  DO NOT EDIT!
// source: ProtoService.proto

package com.example.sofa.rpc.protobuf;

/**
 * Protobuf type {@code com.example.sofa.rpc.protobuf.EchoRequest}
 */
public final class EchoRequest extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:com.example.sofa.rpc.protobuf.EchoRequest)
		EchoRequestOrBuilder {
	private static final long serialVersionUID = 0L;

	// Use EchoRequest.newBuilder() to construct.
	private EchoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private EchoRequest() {
		name_ = "";
		group_ = 0;
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	private EchoRequest(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		}
		int mutable_bitField0_ = 0;
		com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				case 10: {
					java.lang.String s = input.readStringRequireUtf8();

					name_ = s;
					break;
				}
				case 16: {
					int rawValue = input.readEnum();

					group_ = rawValue;
					break;
				}
				default: {
					if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
						done = true;
					}
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		} catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		} finally {
			this.unknownFields = unknownFields.build();
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoRequest_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoRequest_fieldAccessorTable
				.ensureFieldAccessorsInitialized(com.example.sofa.rpc.protobuf.EchoRequest.class,
						com.example.sofa.rpc.protobuf.EchoRequest.Builder.class);
	}

	public static final int NAME_FIELD_NUMBER = 1;
	private volatile java.lang.Object name_;

	/**
	 * <code>string name = 1;</code>
	 */
	@Override
	public java.lang.String getName() {
		java.lang.Object ref = name_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			name_ = s;
			return s;
		}
	}

	/**
	 * <code>string name = 1;</code>
	 */
	@Override
	public com.google.protobuf.ByteString getNameBytes() {
		java.lang.Object ref = name_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			name_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int GROUP_FIELD_NUMBER = 2;
	private int group_;

	/**
	 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
	 */
	@Override
	public int getGroupValue() {
		return group_;
	}

	/**
	 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
	 */
	@Override
	public com.example.sofa.rpc.protobuf.Group getGroup() {
		@SuppressWarnings("deprecation")
		com.example.sofa.rpc.protobuf.Group result = com.example.sofa.rpc.protobuf.Group.valueOf(group_);
		return result == null ? com.example.sofa.rpc.protobuf.Group.UNRECOGNIZED : result;
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (!getNameBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
		}
		if (group_ != com.example.sofa.rpc.protobuf.Group.A.getNumber()) {
			output.writeEnum(2, group_);
		}
		unknownFields.writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		if (!getNameBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
		}
		if (group_ != com.example.sofa.rpc.protobuf.Group.A.getNumber()) {
			size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, group_);
		}
		size += unknownFields.getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof com.example.sofa.rpc.protobuf.EchoRequest)) {
			return super.equals(obj);
		}
		com.example.sofa.rpc.protobuf.EchoRequest other = (com.example.sofa.rpc.protobuf.EchoRequest) obj;

		boolean result = true;
		result = result && getName().equals(other.getName());
		result = result && group_ == other.group_;
		result = result && unknownFields.equals(other.unknownFields);
		return result;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + NAME_FIELD_NUMBER;
		hash = (53 * hash) + getName().hashCode();
		hash = (37 * hash) + GROUP_FIELD_NUMBER;
		hash = (53 * hash) + group_;
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest parseFrom(com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(com.example.sofa.rpc.protobuf.EchoRequest prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code com.example.sofa.rpc.protobuf.EchoRequest}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:com.example.sofa.rpc.protobuf.EchoRequest)
			com.example.sofa.rpc.protobuf.EchoRequestOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoRequest_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.example.sofa.rpc.protobuf.EchoRequest.class,
							com.example.sofa.rpc.protobuf.EchoRequest.Builder.class);
		}

		// Construct using com.example.sofa.rpc.protobuf.EchoRequest.newBuilder()
		private Builder() {
			maybeForceBuilderInitialization();
		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			name_ = "";

			group_ = 0;

			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return com.example.sofa.rpc.protobuf.ProtoServiceModels.internal_static_com_example_sofa_rpc_protobuf_EchoRequest_descriptor;
		}

		@java.lang.Override
		public com.example.sofa.rpc.protobuf.EchoRequest getDefaultInstanceForType() {
			return com.example.sofa.rpc.protobuf.EchoRequest.getDefaultInstance();
		}

		@java.lang.Override
		public com.example.sofa.rpc.protobuf.EchoRequest build() {
			com.example.sofa.rpc.protobuf.EchoRequest result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public com.example.sofa.rpc.protobuf.EchoRequest buildPartial() {
			com.example.sofa.rpc.protobuf.EchoRequest result = new com.example.sofa.rpc.protobuf.EchoRequest(this);
			result.name_ = name_;
			result.group_ = group_;
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof com.example.sofa.rpc.protobuf.EchoRequest) {
				return mergeFrom((com.example.sofa.rpc.protobuf.EchoRequest) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(com.example.sofa.rpc.protobuf.EchoRequest other) {
			if (other == com.example.sofa.rpc.protobuf.EchoRequest.getDefaultInstance())
				return this;
			if (!other.getName().isEmpty()) {
				name_ = other.name_;
				onChanged();
			}
			if (other.group_ != 0) {
				setGroupValue(other.getGroupValue());
			}
			this.mergeUnknownFields(other.unknownFields);
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			com.example.sofa.rpc.protobuf.EchoRequest parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (com.example.sofa.rpc.protobuf.EchoRequest) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			} finally {
				if (parsedMessage != null) {
					mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private java.lang.Object name_ = "";

		/**
		 * <code>string name = 1;</code>
		 */
		@Override
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string name = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string name = 1;</code>
		 */
		public Builder setName(java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			name_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>string name = 1;</code>
		 */
		public Builder clearName() {

			name_ = getDefaultInstance().getName();
			onChanged();
			return this;
		}

		/**
		 * <code>string name = 1;</code>
		 */
		public Builder setNameBytes(com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			name_ = value;
			onChanged();
			return this;
		}

		private int group_ = 0;

		/**
		 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
		 */
		@Override
		public int getGroupValue() {
			return group_;
		}

		/**
		 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
		 */
		public Builder setGroupValue(int value) {
			group_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
		 */
		@Override
		public com.example.sofa.rpc.protobuf.Group getGroup() {
			@SuppressWarnings("deprecation")
			com.example.sofa.rpc.protobuf.Group result = com.example.sofa.rpc.protobuf.Group.valueOf(group_);
			return result == null ? com.example.sofa.rpc.protobuf.Group.UNRECOGNIZED : result;
		}

		/**
		 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
		 */
		public Builder setGroup(com.example.sofa.rpc.protobuf.Group value) {
			if (value == null) {
				throw new NullPointerException();
			}

			group_ = value.getNumber();
			onChanged();
			return this;
		}

		/**
		 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
		 */
		public Builder clearGroup() {

			group_ = 0;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFieldsProto3(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:com.example.sofa.rpc.protobuf.EchoRequest)
	}

	// @@protoc_insertion_point(class_scope:com.example.sofa.rpc.protobuf.EchoRequest)
	private static final com.example.sofa.rpc.protobuf.EchoRequest DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new com.example.sofa.rpc.protobuf.EchoRequest();
	}

	public static com.example.sofa.rpc.protobuf.EchoRequest getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<EchoRequest> PARSER = new com.google.protobuf.AbstractParser<EchoRequest>() {
		@java.lang.Override
		public EchoRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return new EchoRequest(input, extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<EchoRequest> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<EchoRequest> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public com.example.sofa.rpc.protobuf.EchoRequest getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
