// Generated by the ProtocolType buffer compiler.  DO NOT EDIT!
// source: ProtoService.proto

package com.example.sofa.rpc.protobuf;

public interface EchoRequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:com.example.sofa.rpc.protobuf.EchoRequest)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string name = 1;</code>
	 */
	java.lang.String getName();

	/**
	 * <code>string name = 1;</code>
	 */
	com.google.protobuf.ByteString getNameBytes();

	/**
	 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
	 */
	int getGroupValue();

	/**
	 * <code>.com.example.sofa.rpc.protobuf.Group group = 2;</code>
	 */
	com.example.sofa.rpc.protobuf.Group getGroup();
}
