// Generated by the ProtocolType buffer compiler.  DO NOT EDIT!
// source: ProtoService.proto

package com.example.sofa.rpc.protobuf;

/**
 * Protobuf enum {@code com.example.sofa.rpc.protobuf.Group}
 */
public enum Group implements com.google.protobuf.ProtocolMessageEnum {
	/**
	 * <code>A = 0;</code>
	 */
	A(0),
	/**
	 * <code>B = 1;</code>
	 */
	B(1), UNRECOGNIZED(-1),;

	/**
	 * <code>A = 0;</code>
	 */
	public static final int A_VALUE = 0;
	/**
	 * <code>B = 1;</code>
	 */
	public static final int B_VALUE = 1;

	@Override
	public final int getNumber() {
		if (this == UNRECOGNIZED) {
			throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
		}
		return value;
	}

	/**
	 * @deprecated Use {@link #forNumber(int)} instead.
	 */
	@java.lang.Deprecated
	public static Group valueOf(int value) {
		return forNumber(value);
	}

	public static Group forNumber(int value) {
		switch (value) {
		case 0:
			return A;
		case 1:
			return B;
		default:
			return null;
		}
	}

	public static com.google.protobuf.Internal.EnumLiteMap<Group> internalGetValueMap() {
		return internalValueMap;
	}

	private static final com.google.protobuf.Internal.EnumLiteMap<Group> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Group>() {
		@Override
		public Group findValueByNumber(int number) {
			return Group.forNumber(number);
		}
	};

	@Override
	public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
		return getDescriptor().getValues().get(ordinal());
	}

	@Override
	public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
		return getDescriptor();
	}

	public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
		return com.example.sofa.rpc.protobuf.ProtoServiceModels.getDescriptor().getEnumTypes().get(0);
	}

	private static final Group[] VALUES = values();

	public static Group valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
		if (desc.getType() != getDescriptor()) {
			throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
		}
		if (desc.getIndex() == -1) {
			return UNRECOGNIZED;
		}
		return VALUES[desc.getIndex()];
	}

	private final int value;

	private Group(int value) {
		this.value = value;
	}

	// @@protoc_insertion_point(enum_scope:com.example.sofa.rpc.protobuf.Group)
}
