// Generated by the ProtocolType buffer compiler.  DO NOT EDIT!
// source: user_login.proto

package com.boomsecret.protobuf;

public final class MessageUserLogin {
	private MessageUserLogin() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface MessageUserLoginRequestOrBuilder extends
			// @@protoc_insertion_point(interface_extends:MessageUserLoginRequest)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string username = 1;</code>
		 */
		java.lang.String getUsername();

		/**
		 * <code>string username = 1;</code>
		 */
		com.google.protobuf.ByteString getUsernameBytes();

		/**
		 * <code>string password = 2;</code>
		 */
		java.lang.String getPassword();

		/**
		 * <code>string password = 2;</code>
		 */
		com.google.protobuf.ByteString getPasswordBytes();
	}

	/**
	 * Protobuf type {@code MessageUserLoginRequest}
	 */
	public static final class MessageUserLoginRequest extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:MessageUserLoginRequest)
			MessageUserLoginRequestOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use MessageUserLoginRequest.newBuilder() to construct.
		private MessageUserLoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private MessageUserLoginRequest() {
			username_ = "";
			password_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private MessageUserLoginRequest(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						username_ = s;
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						password_ = s;
						break;
					}
					default: {
						if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginRequest_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.class,
							com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.Builder.class);
		}

		public static final int USERNAME_FIELD_NUMBER = 1;
		private volatile java.lang.Object username_;

		/**
		 * <code>string username = 1;</code>
		 */
		@Override
		public java.lang.String getUsername() {
			java.lang.Object ref = username_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				username_ = s;
				return s;
			}
		}

		/**
		 * <code>string username = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getUsernameBytes() {
			java.lang.Object ref = username_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				username_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PASSWORD_FIELD_NUMBER = 2;
		private volatile java.lang.Object password_;

		/**
		 * <code>string password = 2;</code>
		 */
		@Override
		public java.lang.String getPassword() {
			java.lang.Object ref = password_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				password_ = s;
				return s;
			}
		}

		/**
		 * <code>string password = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getPasswordBytes() {
			java.lang.Object ref = password_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				password_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!getUsernameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
			}
			if (!getPasswordBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!getUsernameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
			}
			if (!getPasswordBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest)) {
				return super.equals(obj);
			}
			com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest other = (com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest) obj;

			boolean result = true;
			result = result && getUsername().equals(other.getUsername());
			result = result && getPassword().equals(other.getPassword());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + USERNAME_FIELD_NUMBER;
			hash = (53 * hash) + getUsername().hashCode();
			hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
			hash = (53 * hash) + getPassword().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code MessageUserLoginRequest}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:MessageUserLoginRequest)
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginRequest_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginRequest_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.class,
								com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.Builder.class);
			}

			// Construct using
			// com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				username_ = "";

				password_ = "";

				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginRequest_descriptor;
			}

			@java.lang.Override
			public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest getDefaultInstanceForType() {
				return com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.getDefaultInstance();
			}

			@java.lang.Override
			public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest build() {
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest buildPartial() {
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest result = new com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest(
						this);
				result.username_ = username_;
				result.password_ = password_;
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return (Builder) super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest) {
					return mergeFrom((com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest other) {
				if (other == com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest.getDefaultInstance()) {
					return this;
				}
				if (!other.getUsername().isEmpty()) {
					username_ = other.username_;
					onChanged();
				}
				if (!other.getPassword().isEmpty()) {
					password_ = other.password_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest) e
							.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private java.lang.Object username_ = "";

			/**
			 * <code>string username = 1;</code>
			 */
			@Override
			public java.lang.String getUsername() {
				java.lang.Object ref = username_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					username_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string username = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getUsernameBytes() {
				java.lang.Object ref = username_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					username_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string username = 1;</code>
			 */
			public Builder setUsername(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				username_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string username = 1;</code>
			 */
			public Builder clearUsername() {

				username_ = getDefaultInstance().getUsername();
				onChanged();
				return this;
			}

			/**
			 * <code>string username = 1;</code>
			 */
			public Builder setUsernameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				username_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object password_ = "";

			/**
			 * <code>string password = 2;</code>
			 */
			@Override
			public java.lang.String getPassword() {
				java.lang.Object ref = password_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					password_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string password = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getPasswordBytes() {
				java.lang.Object ref = password_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					password_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public Builder setPassword(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				password_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public Builder clearPassword() {

				password_ = getDefaultInstance().getPassword();
				onChanged();
				return this;
			}

			/**
			 * <code>string password = 2;</code>
			 */
			public Builder setPasswordBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				password_ = value;
				onChanged();
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:MessageUserLoginRequest)
		}

		// @@protoc_insertion_point(class_scope:MessageUserLoginRequest)
		private static final com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest();
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<MessageUserLoginRequest> PARSER = new com.google.protobuf.AbstractParser<MessageUserLoginRequest>() {
			@java.lang.Override
			public MessageUserLoginRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new MessageUserLoginRequest(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<MessageUserLoginRequest> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<MessageUserLoginRequest> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginRequest getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface MessageUserLoginResponseOrBuilder extends
			// @@protoc_insertion_point(interface_extends:MessageUserLoginResponse)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string access_token = 1;</code>
		 */
		java.lang.String getAccessToken();

		/**
		 * <code>string access_token = 1;</code>
		 */
		com.google.protobuf.ByteString getAccessTokenBytes();

		/**
		 * <code>string username = 2;</code>
		 */
		java.lang.String getUsername();

		/**
		 * <code>string username = 2;</code>
		 */
		com.google.protobuf.ByteString getUsernameBytes();
	}

	/**
	 * Protobuf type {@code MessageUserLoginResponse}
	 */
	public static final class MessageUserLoginResponse extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:MessageUserLoginResponse)
			MessageUserLoginResponseOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use MessageUserLoginResponse.newBuilder() to construct.
		private MessageUserLoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private MessageUserLoginResponse() {
			accessToken_ = "";
			username_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private MessageUserLoginResponse(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						accessToken_ = s;
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						username_ = s;
						break;
					}
					default: {
						if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginResponse_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.class,
							com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.Builder.class);
		}

		public static final int ACCESS_TOKEN_FIELD_NUMBER = 1;
		private volatile java.lang.Object accessToken_;

		/**
		 * <code>string access_token = 1;</code>
		 */
		@Override
		public java.lang.String getAccessToken() {
			java.lang.Object ref = accessToken_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				accessToken_ = s;
				return s;
			}
		}

		/**
		 * <code>string access_token = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getAccessTokenBytes() {
			java.lang.Object ref = accessToken_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				accessToken_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int USERNAME_FIELD_NUMBER = 2;
		private volatile java.lang.Object username_;

		/**
		 * <code>string username = 2;</code>
		 */
		@Override
		public java.lang.String getUsername() {
			java.lang.Object ref = username_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				username_ = s;
				return s;
			}
		}

		/**
		 * <code>string username = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getUsernameBytes() {
			java.lang.Object ref = username_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				username_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!getAccessTokenBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
			}
			if (!getUsernameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (!getAccessTokenBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
			}
			if (!getUsernameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse)) {
				return super.equals(obj);
			}
			com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse other = (com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse) obj;

			boolean result = true;
			result = result && getAccessToken().equals(other.getAccessToken());
			result = result && getUsername().equals(other.getUsername());
			result = result && unknownFields.equals(other.unknownFields);
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
			hash = (53 * hash) + getAccessToken().hashCode();
			hash = (37 * hash) + USERNAME_FIELD_NUMBER;
			hash = (53 * hash) + getUsername().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code MessageUserLoginResponse}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:MessageUserLoginResponse)
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginResponse_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginResponse_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.class,
								com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.Builder.class);
			}

			// Construct using
			// com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				accessToken_ = "";

				username_ = "";

				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.boomsecret.protobuf.MessageUserLogin.internal_static_MessageUserLoginResponse_descriptor;
			}

			@java.lang.Override
			public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse getDefaultInstanceForType() {
				return com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.getDefaultInstance();
			}

			@java.lang.Override
			public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse build() {
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse buildPartial() {
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse result = new com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse(
						this);
				result.accessToken_ = accessToken_;
				result.username_ = username_;
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return (Builder) super.clone();
			}

			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return (Builder) super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse) {
					return mergeFrom((com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse other) {
				if (other == com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse.getDefaultInstance()) {
					return this;
				}
				if (!other.getAccessToken().isEmpty()) {
					accessToken_ = other.accessToken_;
					onChanged();
				}
				if (!other.getUsername().isEmpty()) {
					username_ = other.username_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse) e
							.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private java.lang.Object accessToken_ = "";

			/**
			 * <code>string access_token = 1;</code>
			 */
			@Override
			public java.lang.String getAccessToken() {
				java.lang.Object ref = accessToken_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					accessToken_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string access_token = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getAccessTokenBytes() {
				java.lang.Object ref = accessToken_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					accessToken_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string access_token = 1;</code>
			 */
			public Builder setAccessToken(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				accessToken_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string access_token = 1;</code>
			 */
			public Builder clearAccessToken() {

				accessToken_ = getDefaultInstance().getAccessToken();
				onChanged();
				return this;
			}

			/**
			 * <code>string access_token = 1;</code>
			 */
			public Builder setAccessTokenBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				accessToken_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object username_ = "";

			/**
			 * <code>string username = 2;</code>
			 */
			@Override
			public java.lang.String getUsername() {
				java.lang.Object ref = username_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					username_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string username = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getUsernameBytes() {
				java.lang.Object ref = username_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					username_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string username = 2;</code>
			 */
			public Builder setUsername(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				username_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string username = 2;</code>
			 */
			public Builder clearUsername() {

				username_ = getDefaultInstance().getUsername();
				onChanged();
				return this;
			}

			/**
			 * <code>string username = 2;</code>
			 */
			public Builder setUsernameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				username_ = value;
				onChanged();
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFieldsProto3(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:MessageUserLoginResponse)
		}

		// @@protoc_insertion_point(class_scope:MessageUserLoginResponse)
		private static final com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse();
		}

		public static com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<MessageUserLoginResponse> PARSER = new com.google.protobuf.AbstractParser<MessageUserLoginResponse>() {
			@java.lang.Override
			public MessageUserLoginResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new MessageUserLoginResponse(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<MessageUserLoginResponse> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<MessageUserLoginResponse> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public com.boomsecret.protobuf.MessageUserLogin.MessageUserLoginResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_MessageUserLoginRequest_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_MessageUserLoginRequest_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_MessageUserLoginResponse_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_MessageUserLoginResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\020user_login.proto\"=\n\027MessageUserLoginRe"
				+ "quest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001("
				+ "\t\"B\n\030MessageUserLoginResponse\022\024\n\014access_"
				+ "token\030\001 \001(\t\022\020\n\010username\030\002 \001(\tB+\n\027com.boo"
				+ "msecret.protobufB\020MessageUserLoginb\006prot" + "o3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			@Override
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_MessageUserLoginRequest_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_MessageUserLoginRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_MessageUserLoginRequest_descriptor, new java.lang.String[] { "Username", "Password", });
		internal_static_MessageUserLoginResponse_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_MessageUserLoginResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_MessageUserLoginResponse_descriptor,
				new java.lang.String[] { "AccessToken", "Username", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
